version: '3.3'

services:
  app:
    image: node:18-alpine
    container_name: nextjs-app
    working_dir: /usr/src/app
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
      - /usr/src/app/.next
    ports:
      - "4200:4200"
    environment:
      - NODE_ENV=production
    command: sh -c "npm ci && npm run build && npm start"