version: '3.8'

services:
  web:
    image: node:18-alpine
    container_name: stream-platform
    working_dir: /app
    ports:
      - "4200:4200"
    volumes:
      - ./:/app
      - /app/node_modules
    environment:
      NODE_ENV: development
    command: sh -c "npm install && npm run dev"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
